Subscriptia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('product.urls')),
] 

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = "account"

urlpatterns = [
    path('', views.profile, name="profile"),
    path('login/', views.log_in, name="login"),
    path('register/', views.register, name="register"),
    path('logout', views.log_out, name="logout"),
]

product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cardview, name="cardview"),
    path('<int:product_id>/details/', views.product_single, name="product_single"),
    path('add', views.add_product, name="add_product"),
    path('invoice/',views.invoice, name="invoice"),
    path('about_us/',views.about_us, name="about_us"),
    path('add_to_cart/<id>',views.add_to_cart, name="cart"),
    path('wishlist/<id>',views.wishlist, name="wishlist"),
    path('wish_list/<id>',views.r_wishlist, name="r_wishlist"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.files.storage import FileSystemStorage

# Create your models here.

class User(AbstractUser):
    is_admin = models.BooleanField('Is_admin', default=False)
    is_employee = models.BooleanField('Is_employee', default=False)
    is_customer = models.BooleanField('Is_customer', default=True)

class Profile(models.Model):
    fs = FileSystemStorage()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', blank=True, null=True)
    dob = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile' #show how we want it to be displayed

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Profile

class ProfileForm(forms.Form):
    class meta:
        models = Profile
        fields = '__all__'

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = User
        fields = (
            'username', 
            'email', 
            'password1', 
            'password2',
            'is_admin',
            'is_employee',
            'is_customer',
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .models import User, Profile

# Create your views here.

def log_in(request):
    form_msg = None
    if request.method == "POST":
        uname = request.POST.get('username')
        pword = request.POST.get('password')
        print(uname, pword)

        user = authenticate(username=uname, password=pword)
        
        if user is not None:
            print("Logged in.")
            login(request, user)
            return render(request,"home.html")
        else:
            print("Wrong input.")
            form_msg = "Username or Password is wrong."
            return render(request, "accounts/login.html", {'form_msg': form_msg})
    print("logged out")
    return render(request, "accounts/login.html", {'form_msg': form_msg})


def register(request):
    form_msg = None
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        email_exist = User.objects.all().filter(email=email).exists()
        if not email_exist:
            try:
                myuser = User.objects.create_user(username=username, email=email, password=password)
                myuser.save()
                profile = Profile(user=myuser)
                profile.save()
                return redirect('account:login')
            except Exception:
                form_msg = "Username already taken."
                return render(request, "accounts/register.html", {'form_msg': form_msg})
        else:
            form_msg = "Email already taken."
            return render(request, "accounts/register.html", {'form_msg': form_msg})

    return render(request, "accounts/register.html", {'form_msg': form_msg})


def log_out(request):
    logout(request)
    return redirect('account:login')

def profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method == "POST":
        if request.FILES.get('image-file'):
            image_file = request.FILES.get('image-file')
            profile.image = image_file
        profile.dob = request.POST.get('birthday')
        profile.save()
        user.first_name = request.POST.get('first-name')
        user.last_name = request.POST.get('last-name')
        user.email = request.POST.get('email-name')
        pword = request.POST.get('user-password')
        if pword is not (None or ""):
            user.set_password(pword)
            user.save()
            logout(request)
            return redirect('account:login')
        user.save()
    return render(request, "accounts/profile.html", {"user": user, "profile":profile})



# def home_page(request):
#     if request.method == "POST":
#         uname = request.POST.get('username')
#         pword = request.POST.get('password')

#         user = authenticate(username=uname, password=pword)

#         if user is not None:
#             login(request, user)
#             return render(request, "home/index.html")
#         else:
#             messages.error(request, "Bad Credentials")
#             return redirect('home_page')
#     return render(request, "home/index.html")


# def register_page(request):
#     if request.method == "POST":
#         firstname = request.POST.get('firstName')
#         lastname = request.POST.get('lastName')
#         email = request.POST.get('email')
#         username = request.POST.get('userName')
#         password = request.POST.get('password')
#         repassword = request.POST.get('repassword')

#         if password == repassword:
#             myuser = User.objects.create_user(username, email, password)
#             myuser.first_name = firstname
#             myuser.last_name = lastname

#             myuser.save()
#             messages.success(request, "Your Account has been successfully created.")
#             redirect('home_page')
#         else:
#             messages.error(request, "Password did not match.")

#     return render(request, "home/register.html")


# def log_out(request):
#     logout(request)
#     return redirect('home_page')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Banner Area -->
    <section id="common_banner_one">
        <div class="container ">
            <div class="row">
                <div class="col-lg-12">
                    <div class="common_banner_text">
                        <h2>Login</h2>
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><i class="fas fa-slash"></i></li>
                            <li class="active">Login</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Checkout-Area -->
    <section id="login_area" class="ptb-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3 col-md-12 col-sm-12 col-12">
                    <div class="account_form">
                        <h3>Login</h3>
                        <form action="{% url 'account:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="default-form-box">
                                <label>Username <span>*</span></label>
                                <input type="text" class="form-control"
                                name="username">
                            </div>
                            <div class="default-form-box">
                                <label>Password <span>*</span></label>
                                <input type="password" class="form-control"
                                name="password">
                            </div>
                            <div class="login_submit">
                                <button class="theme-btn-one btn-black-overlay btn_md" type="submit">login</button>
                            </div>

                            <a href="{% url 'account:register' %}">Create Your Account?</a>
                        </form>
                        {% if form_msg %} {{ form_msg }} {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Banner Area -->
    <section id="common_banner_one">
        <div class="container ">
            <div class="row">
                <div class="col-lg-12">
                    <div class="common_banner_text">
                        <h2>My Account</h2>
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><i class="fas fa-slash"></i></li>
                            <li class="active">My Account</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- My-account-area-Area -->
    <section id="my-account_area" class="ptb-100">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <!-- Nav tabs -->
                    <div class="dashboard_tab_button">
                        <ul role="tablist" class="nav flex-column dashboard-list">
                            <li><a href="#!" data-bs-toggle="tab" data-bs-target="#dashboard" class=" active"><i
                                        class="fas fa-tachometer-alt"></i>Dashboard</a></li>
                            <li> <a href="#!" data-bs-toggle="tab" data-bs-target="#orders"><i
                                        class="fas fa-cart-arrow-down"></i>Orders</a></li>
                            <li><a href="#!" data-bs-toggle="tab" data-bs-target="#downloads"><i
                                        class="fas fa-cloud-download-alt"></i>Downloads</a></li>
                            <li><a href="#!" data-bs-toggle="tab" data-bs-target="#account-details"><i
                                        class="fas fa-user"></i>Account
                                    details</a>
                            </li>
                            <li><a href="{% url 'account:logout' %}" class=""><i class="fas fa-sign-out-alt"></i>logout</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade show active" id="dashboard">
                            <div class="myaccount-content">
                                {% if user.is_customer %}
                                    <h4 class="title">Dashboard </h4>
                                {% elif user.is_employee %}
                                    <h4 class="title">Employee Dashboard </h4>
                                {% endif %}
                                <p>From your account dashboard. you can easily check &amp; view your <a href="#">recent
                                        orders</a>, manage your <a href="#">shipping and billing addresses</a> and <a
                                        href="#">Edit your password and account details.</a></p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="orders">
                            <div class="myaccount-content">
                                <h4 class="title">Orders </h4>
                                <div class="table_page table-responsive">
                                    <table>
                                        <thead>
                                            <tr>
                                                <th>Order</th>
                                                <th>Date</th>
                                                <th>Status</th>
                                                <th>Total</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1</td>
                                                <td>May 10, 2018</td>
                                                <td><span class="success">Completed</span></td>
                                                <td>$25.00 for 1 item </td>
                                                <td><a href="cart.html" class="view">view</a></td>
                                            </tr>
                                            <tr>
                                                <td>2</td>
                                                <td>May 10, 2018</td>
                                                <td>Processing</td>
                                                <td>$17.00 for 1 item </td>
                                                <td><a href="cart.html" class="view">view</a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                        <div class="tab-pane fade" id="downloads">
                            <div class="myaccount-content">
                                <h4 class="title">Downloads </h4>
                                <div class="table_page table-responsive">
                                    <table>
                                        <thead>
                                            <tr>
                                                <th>Product</th>
                                                <th>Downloads</th>
                                                <th>Expires</th>
                                                <th>Download</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Shopnovilla - Free Real Estate PSD Template</td>
                                                <td>May 10, 2018</td>
                                                <td><span class="danger">Expired</span></td>
                                                <td><a href="#" class="view">Click Here To Download Your File</a></td>
                                            </tr>
                                            <tr>
                                                <td>Organic - ecommerce html template</td>
                                                <td>Sep 11, 2018</td>
                                                <td>Never</td>
                                                <td><a href="#" class="view">Click Here To Download Your File</a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>


                        </div>
                        <div class="tab-pane fade" id="account-details">
                            <div class="myaccount-content">
                                <h4 class="title">Account details</h4>
                                <div class="login_form_container">
                                    <div class="account_details_form">
                                        <form action="{% url 'account:profile' %}" method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="img_profiles">
                                                <img src="{{ profile.image.url }}" alt="img">
                                            </div>
                                            <br>
                                            <div class="mb-3">
                                                <label for="formFile" class="form-label">Edit Profile Picture</label>
                                                <input type="file" name="image-file" class="form-control" id="formFile" accept=".jpg, .png">
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>First Name</label>
                                                <input type="text" name="first-name" class="form-control" value="{{ user.first_name }}">
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>Last Name</label>
                                                <input type="text" name="last-name" class="form-control" value="{{ user.last_name }}">
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>Email</label>
                                                <input type="text" name="email-name" value="{{ user.email }}"
                                                    class="form-control">
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>New Password</label>
                                                <input type="password" name="user-password" value=""
                                                    class="form-control">
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>Birthdate</label>
                                                <input type="date" name="birthday" value="{{ profile.dob }}"
                                                    class="form-control">
                                            </div>
                                            <span class="example">
                                                (E.g.: 05/31/1970)
                                            </span>
                                            <br>
                                            <div class="save_button mt-3">
                                                    <button class="theme-btn-one btn-black-overlay btn_sm" type="submit"> Update </button> 
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %} {% block content %}
<!-- Banner Area -->
<section id="common_banner_one">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="common_banner_text">
          <h2>Register</h2>
          <ul>
            <li><a href="index.html">Home</a></li>
            <li><i class="fas fa-slash"></i></li>
            <li class="active">Register</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Register-Area -->
<section id="login_area" class="ptb-100">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-12 col-sm-12 col-12">
        <div class="account_form">
          <h3>Register</h3>
          <form action="{% url 'account:register' %}" method="POST">
            {% csrf_token %}
            <div class="default-form-box">
              <label>Username <span>*</span></label>
              <input type="text" class="form-control" name="username" />
            </div>
            <div class="default-form-box">
              <label>Email <span>*</span></label>
              <input type="email" class="form-control" name="email" required/>
            </div>
            <div class="default-form-box">
              <label>Password <span>*</span></label>
              <input type="password" class="form-control" name="password" />
            </div>
            <div class="login_submit">
              <button
                class="theme-btn-one btn-black-overlay btn_md"
                type="submit"
              >
                Register
              </button>
            </div>
          </form>
          {% if form_msg %} {{ form_msg }} {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}