Subscriptia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('product.urls')),
] 

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cardview, name="cardview"),
    path('<int:product_id>/details/', views.product_single, name="product_single"),
    path('add', views.add_product, name="add_product"),
    path('invoice/',views.invoice, name="invoice"),
    path('about_us/',views.about_us, name="about_us"),
    path('add_to_cart/<id>',views.add_to_cart, name="cart"),
    path('wishlist/<id>',views.wishlist, name="wishlist"),
    path('wish_list/<id>',views.r_wishlist, name="r_wishlist"),
]

product/models.py
from django.db import models
from accounts.models import *
from datetime import timezone

# Create your models here.

CATEGORIES = (('None', 'None'), ('News', 'News'), ('Books', 'Books'), ('Streaming', 'Streaming'),
 ('Software', 'Software'), ('Web', 'Web'), ('Design', 'Design'), ('Presentation', 'Presentation'),    ('Educational', 'Educational'), ('Streaming', 'Streaming'), ('Video', 'Video'), ('Writing',
                                                                   'Writing'), ('Travel', 'Travel'), ('Blog', 'Blog'),
 ('E-commerce', 'E-commerce'), ('Photos', 'Photo Editing'), ('Videos', 'Video Editing'), ('Music', 'Music'))


RANGE = ((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5))


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, default="")
    slug = models.SlugField(unique=True, max_length=30)
    rating = models.PositiveIntegerField(default=0, choices=RANGE)
    rating_amount = models.PositiveBigIntegerField(default=0)
    in_wishlist = models.PositiveIntegerField(default=0)
    in_cart = models.PositiveIntegerField(default=0)
    image = models.ImageField(null=True, blank=True,
                              upload_to='products/product_images/')
    plan_name = models.CharField(max_length=100, default='')
    price = models.FloatField(default=0.00)
    discount = models.FloatField(default=-0.00)
    category = models.CharField(
        max_length=200, choices=CATEGORIES, default=None)
    time_added = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return f'{self.name}: {self.description}'


class BannerImg(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    banner = models.ImageField(null=True, blank=True, upload_to="products/banner_images/")

class CartProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return str(self.id)


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(blank=True, null=True)
    
    class Meta:
        unique_together = ['user', 'product']

class ReviewComment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    comment = models.TextField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('created_at',)


class Wishlist_Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

contacts/forms.py
from django import forms
from django.forms import ModelForm
from . models import QA

class QAForm(ModelForm):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control"} ) )
    ques = forms.CharField(max_length=500, widget=forms.Textarea(attrs={"class": "form-control"} ) )
    ans = forms.CharField(max_length=500, blank=True, null=True, widget=forms.Textarea(attrs={"class": "form-control"} ) )


    class Meta:
        model = QA
        fields = ['name', 'ques', 'ans']

templates/about_us.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<!-- Banner Area -->
<section id="common_banner_one">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="common_banner_text">
            <h2 style="font-style: bold">About</h2>
            <ul>
              <li><a href="index.html">Home</a></li>
              <li><i class="fas fa-slash"></i></li>
              <li class="active">About</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- About-Top -->
  <section id="about-top" class="ptb-100">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12 col-12">
          <div class="about_top_img">
            <img src="{% static 'assets/img/team/us.jpeg' %}" alt="img" />
          </div>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12 col-12">
          <div class="about_top_left_content">
            <h2>
              ABOUT OUR
              <span style="color: rgb(195, 22, 22)">Subscriptia</span> website
            </h2>
            <h4>
              We believe that every project existing in digital world is a
              result of an idea and every idea has a cause.
            </h4>
            <p>
              For this reason, our each design serves an idea. Our strength in
              design is reflected by our name, our care for details. Our
              specialist won't be afraid to go extra miles just to approach
              near perfection. We don't require everything to be perfect, but
              we need them to be perfectly cared for.
            </p>
            <p>
              That's a reason why we are willing to give contributions at
              best.Not a single detail is missed out under Billey's
              professional eyes. The amount of dedication and effort equals to
              the level of passion and determination. Get better, together as
              one.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- About progressbar -->
  <section id="about_progressbar" class="ptb-100">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="about_progressbar_content">
            <h2>Functionality meets perfection</h2>
            <p>
              In today’s day and age, one cannot underestimate the importance
              of design, the art of creating striking visuals to move and
              captivate your audience. And as the world becomes more and more
              digitized with each passing second, the importance of graphic
              design has been rocketed to the top. html, css, js, python
            </p>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="custom-progress m-t-40">
            <h6 class="font--semi-bold mb-2">JavaScript</h6>
            <div class="progress mb-5">
              <div class="progress-bar bg-info" style="width: 20%"></div>
            </div>
            <h6 class="font--semi-bold mb-2">Python</h6>
            <div class="progress mb-5">
              <div class="progress-bar bg-success" style="width: 40%"></div>
            </div>
            <h6 class="font--semi-bold mb-2">CSS</h6>
            <div class="progress mb-5">
              <div class="progress-bar bg-warning" style="width: 80%"></div>
            </div>
            <h6 class="font--semi-bold mb-2">HTML</h6>
            <div class="progress">
              <div class="progress-bar bg-danger" style="width: 90%"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Team Area -->
  <section id="team_area" class="ptb-100">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="center_heading">
            <h2>The Python Team</h2>
            <p>This website is developed by students of CSE, MIST.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="team_slider owl-carousel owl-theme">
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/mahdi.jpg' %}" alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Mahdi</h4>
                <span class="team-title">Developer</span>
                <ul class="team-social pos-absolute">
                  <li>
                    <a href="https://github.com/Mahdi3M"
                      ><i class="fab fa-github"></i
                    ></a>
                  </li>
                  <li>
                    <a href="https://www.linkedin.com/in/mahdi3m"
                      ><i class="fab fa-linkedin"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.facebook.com/profile.php?id=100008519318619"
                      ><i class="fab fa-facebook-f"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/sara.jpeg' %}" alt="img" />
              </div>

              <div class="team-content">
                <h4 class="team-name font--bold">Sara</h4>
                <span class="team-title">Developer</span>
                <ul class="team-social pos-absolute">
                  <li>
                    <a href="https://github.com/TasfiaSarah"
                      ><i class="fab fa-github"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.linkedin.com/in/tasfia-sara-a690571b3/"
                      ><i class="fab fa-linkedin"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.facebook.com/profile.php?id=100006125027423&mibextid=LQQJ4d"
                      ><i class="fab fa-facebook-f"></i
                    ></a>
                  </li>

                  <li>
                    <a
                      href="https://www.instagram.com/tash_fia_"
                      ><i class="fab fa-instagram"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/nazo.jpeg' %}"  alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Nazifa</h4>
                <span class="team-title">Developer</span>
                <ul class="team-social pos-absolute">
                  <li>
                    <a href="https://github.com/SadiaNurNazifa"
                      ><i class="fab fa-github"></i
                    ></a>
                  </li>
                  <li>
                    <a href="https://www.linkedin.com/in/sadianurnazifa/"
                      ><i class="fab fa-linkedin"></i
                    ></a>
                  </li>
                  <li>
                    <a href="https://www.facebook.com/nazifanur"
                      ><i class="fab fa-facebook-f"></i
                    ></a>
                  </li>

                  <li>
                    <a href="https://www.instagram.com/nurzofa/"
                      ><i class="fab fa-instagram"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/sakib.jpg' %}"  alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Sakib</h4>
                <span class="team-title">Developer</span>
                <ul class="team-social pos-absolute">
                  <li>
                    <a href="https://github.com/Shakib1633"
                      ><i class="fab fa-github"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.facebook.com/profile.php?id=100012529662822"
                      ><i class="fab fa-facebook-f"></i
                    ></a>
                  </li>

                  <li>
                    <a
                      href="https://www.snapchat.com/add/t.shakib1633?share_id=U9jk9qvKkZI&locale=en-US"
                      ><i class="fab fa-snapchat"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/shado.jpg' %}"  alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Shadmanee</h4>
                <span class="team-title">Developer</span>
                <ul class="team-social pos-absolute">
                  <li>
                    <a href="https://github.com/shadmanee"
                      ><i class="fab fa-github"></i
                    ></a>
                  </li>
                  <li>
                    <a href="https://www.linkedin.com/in/shadmanee-tasneem"
                      ><i class="fab fa-linkedin"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.facebook.com/lolydoucare?mibextid=ZbWKwL"
                      ><i class="fab fa-facebook-f"></i
                    ></a>
                  </li>

                  <li>
                    <a
                      href="https://instagram.com/shadmaneey?igshid=YmJhNjkzNzY="
                      ><i class="fab fa-instagram"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>

            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/tajakka.jpg' %}"  alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Tajakka</h4>
                <span class="team-title">Developer</span>
                <ul class="team-social pos-absolute">
                  <li>
                    <a href="https://github.com/Tajakka27"
                      ><i class="fab fa-github"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.linkedin.com/in/tajakka-binte-aziz-30889122b/"
                      ><i class="fab fa-linkedin"></i
                    ></a>
                  </li>
                  <li>
                    <a href="https://www.facebook.com/tajakka.aziz"
                      ><i class="fab fa-facebook-f"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/shantona.jpg' %}"  alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Shantona</h4>
                <span class="team-title">Developer</span>
                <ul class="team-social pos-absolute">
                  <li>
                    <a href="https://github.com/Santona00"
                      ><i class="fab fa-github"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.linkedin.com/in/chowdhury-farjana-tur-santona-5b18b61b5"
                      ><i class="fab fa-linkedin"></i
                    ></a>
                  </li>
                  <li>
                    <a
                      href="https://www.facebook.com/madoka.temari?mibextid=ZbWKwL"
                      ><i class="fab fa-facebook-f"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/sebas.jpg' %}" alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Sevas</h4>
                <span class="team-title">Developer</span>
              </div>
            </div>
            <div class="team-single">
              <div class="team-img">
                <img src="{% static 'assets/img/team/shejuti.jpg' %}"  alt="img" />
              </div>
              <div class="team-content">
                <h4 class="team-name font--bold">Shejuti</h4>
                <span class="team-title">Developer</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock %}

templates/add-product_priv.html
{% extends 'base.html' %}
{% block content %}

<!-- Banner Area -->
<section id="common_banner_one">
    <div class="container ">
        <div class="row">
            <div class="col-lg-12">
                <div class="common_banner_text">
                    <h2>Add Product</h2>
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><i class="fas fa-slash"></i></li>
                        <li class="active">Add Product</li>
                    </ul>
                    <ul>
                        {% comment %} <div class="col-lg-12">
                            <div class="image-input">
                                {{product.banner}}                                    
                                <label for="id_banner" class="image-button">
                                    <i class="fa fa-image"></i>Choose Banner Image</label>
                            </div>
                        </div> {% endcomment %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Add Product Area -->
<section id="add_product_area" class="ptb-100" onload='getInputElements()'>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="add_product_wrapper">
                    <div class="back_to_area">
                        <a href="vendor.html"><i class="fas fa-long-arrow-alt-left"></i> Back To Dashboard</a>
                    </div>
                    <h3>Add Product</h3>
                    <form action="" method="post" enctype="multipart/form-data" class="add_product_form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12">
                                <h4>Basic Information</h4>
                            </div>
                            <div class="col-lg-12">
                                <div class="image-input">
                                    <input type="file" name="product_image" class="form-control" id="id_image" accept=".jpg, .png">                                                                       
                                    <label for="id_image" class="image-button">
                                    <i class="fa fa-image"></i>Choose Image</label>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="fotm-group">
                                    <label for="id_name">Product Name*</label>
                                    <input type="text" id="id_name" class="form-control" name="product_name"
                                        value="{{product.name}}">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="fotm-group">
                                    <label for="id_description">Product Description*</label>
                                    <textarea style="min-height: 200px;" id="id_description" class="form-control" name="product_desc"
                                        value="{{product.description}}"></textarea>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <h4 style="margin-top: 50px; margin-bottom: 20px;">Categories</h4>
                            </div>
                            <div class="col-lg-12">
                                <div class="fotm-group">
                                    <select id="id_category" name="product_category">
                                    {% for c in categories %}                                        
                                            <option value="{{c}}">{{c}}</option>                                                                            
                                    {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <h4 style="margin-top: 50px; margin-bottom: 20px;">Subscription Plan</h4>
                            </div>
                            <div class="col-lg-6">
                                <div class="fotm-group">
                                    <label for="id_plan_name">Plan Name*</label>                                    
                                    <input type="text" id="id_plan_name" class="form-control" name="product_plan_name"
                                        value="{{product.plan_name}}">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="fotm-group">
                                    <label for="id_price">Price*</label>                                    
                                    <input type="number" step = "0.01" id="id_price" class="form-control" name="product_price"
                                        value="{{product.price}}">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="fotm-group">
                                    <label for="id_discount">Discount*</label>                                    
                                    <input type="number" step="0.01" id="id_discount" class="form-control" name="product_discount"
                                        value="{{product.discount}}">
                                </div>
                            </div>                            
                            <div class="col-lg-12">
                                <div class="btn_right_table">
                                    <button class="theme-btn-one bg-black btn_sm" type='submit'>Add Product</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/add_to_cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <!-- Banner Area -->
 <section id="my-account_area" class="ptb-100">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <!-- Nav tabs -->
<!--                    <div class="dashboard_tab_button" >-->
<!--                        <ul role="tablist" class="nav flex-column dashboard-list" >-->
<!--                            {% for c in cart %}-->
<!--                           <li> <a href="#!" data-bs-toggle="tab" data-bs-target="#orders" >{{c.product.name}} {{ c.product.plan_name }}-->
<!--                            </a></li>-->
<!--&lt;!&ndash;                            <li> <a href="#!" data-bs-toggle="tab" data-bs-target="#orders">Spotify</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                             <li> <a href="#!" data-bs-toggle="tab" data-bs-target="#orders">Udemy</a></li>&ndash;&gt;-->
<!--                            {% endfor %}-->
<!--                        </ul>-->
<!--                    </div>-->
                </div>
                <div class="col-sm-10 col-md-10 col-lg-7">
                    <!-- Tab panes -->
<!--                    <div class="tab-content dashboard_content">-->
<!--                        <div class="tab-pane fade show active" id="orders">-->
<!--                            <div class="myaccount-content">-->
<!--                                <h4 class="title"> </h4>-->
<!--                                    <form method="POST">-->
<!--                                        <div class="col-lg-12 col-md-12 col-sm-12 col-8">-->
<!--                                            <div class="form-group">-->
<!--                                                <label for="email">Email Address</label>-->
<!--                                                <input class="form-control"  type="email" id="email"-->
<!--                                                    placeholder="info@gmail.com *" required>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="col-lg-12 col-md-12 col-sm-12 col-8">-->
<!--                                            <div class="form-group">-->
<!--                                                <label for="password">Password</label>-->
<!--                                                <input class="form-control"  type="password" id="Password"-->
<!--                                                    placeholder="password *" required>-->
<!--                                            </div>-->
<!--                                        </div>-->

<!--                                        <div class="cart_submit">-->
<!--                                            <center><button class="theme-btn-one btn-black-overlay btn_sm" type="submit">Verify</button></center>-->

<!--                                        </div>-->


<!--                                        <div class="cart_submit">-->
<!--                                            <button class="theme-btn-one btn-black-overlay btn_sm" type="submit">Remove</button>-->
<!--                                        </div>-->
<!--                                    </form>-->

<!--                                </div>-->



<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
        </div>

                            </div>


                        </div>

                      </div>
    </section>

              <div class="col-lg-10 " style="padding-left:26%;padding-bottom: 10%;">
                    <div class="order_review  box-shadow bg-white" >
                        <div class="check-heading">
                            <h3>Details</h3>
                        </div>
                        <div class="table-responsive order_table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Remove</th>
                                        <th>Product</th>
                                        <th>Plan</th>
                                        <th>Price</th>


                                    </tr>
                                </thead>
                                <tbody>
                                {% for c in cart %}
                                    <tr>
                                        <td class="product_remove" style="padding-left:7% ;"><a href="{% url 'r_cart' c.product.id  %}"><i class="far fa-trash-alt"></i></a></td>
                                        <td>{{c.product.name}} </td>
                                        <td>{{c.product.plan_name}} </td>
                                        <td>&#2547;{{c.product.price}}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <th >Total</th>
                                        <td class="product-subtotal" >&#2547; {{subtotal}}</td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="order_review bg-white">
                        <div class="check-heading">
                            <h3>Payment</h3>
                        </div>
                        <div class="payment_method">
                            <div class="payment_option">
                                <div class="custome-radio">
                                    <input class="form-check-input" required="" type="radio" name="payment_option"
                                        id="exampleRadios3" value="option3" checked="">
                                    <label class="form-check-label" for="exampleRadios3">Card Payment</label>
                                </div>
                                <div class="custome-radio">
                                    <input class="form-check-input" type="radio" name="payment_option"
                                        id="exampleRadios4" value="option4">
                                    <label class="form-check-label" for="exampleRadios4">BKash  Payment</label>
                                </div>
                            </div>
                                </div>
                            </div>
                            <center>
                            <a href="{% url 'invoice' %}" class="theme-btn-one btn-black-overlay btn_sm">Place Order</a></center>
                        </div>




{% endblock %}